const data = [{
    "product_name": "Honorable",
    "brand": "Meeveo",
    "price": 180.93,
    "quantity": 55,
    "color": "Yellow",
    "size": "XL",
    "material": "polyester",
    "category": "clothing",
    "description": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    "rating": 3.6,
    "availability": false,
    "discount_percentage": 0.98,
    "shipping_cost": 5.26,
    "shipping_time": 1,
    "arrival_date": "11/6/2022",
    "seller_name": "Nlounge",
    "seller_rating": 4.0,
    "seller_location": "Apt 1201",
    "seller_contact": "527-874-6210"
  }, {
    "product_name": "Rev",
    "brand": "Photobug",
    "price": 519.97,
    "quantity": 45,
    "color": "Yellow",
    "size": "L",
    "material": "cotton",
    "category": "home goods",
    "description": "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    "rating": 3.7,
    "availability": true,
    "discount_percentage": 38.31,
    "shipping_cost": 3.33,
    "shipping_time": 4,
    "arrival_date": "5/3/2022",
    "seller_name": "Bubbletube",
    "seller_rating": 1.0,
    "seller_location": "7th Floor",
    "seller_contact": "363-213-9876"
  }, {
    "product_name": "Mrs",
    "brand": "Reallinks",
    "price": 9.37,
    "quantity": 42,
    "color": "Red",
    "size": "XL",
    "material": "cotton",
    "category": "electronics",
    "description": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    "rating": 4.0,
    "availability": true,
    "discount_percentage": 7.33,
    "shipping_cost": 0.19,
    "shipping_time": 13,
    "arrival_date": "1/17/2022",
    "seller_name": "Photobug",
    "seller_rating": 4.1,
    "seller_location": "7th Floor",
    "seller_contact": "724-356-6964"
  }, {
    "product_name": "Dr",
    "brand": "Edgewire",
    "price": 174.45,
    "quantity": 32,
    "color": "Mauv",
    "size": "S",
    "material": "wool",
    "category": "clothing",
    "description": "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    "rating": 1.5,
    "availability": true,
    "discount_percentage": 41.9,
    "shipping_cost": 19.11,
    "shipping_time": 6,
    "arrival_date": "6/19/2022",
    "seller_name": "Gabtype",
    "seller_rating": 4.1,
    "seller_location": "PO Box 6021",
    "seller_contact": "952-272-0345"
  }, {
    "product_name": "Dr",
    "brand": "Voonix",
    "price": 539.12,
    "quantity": 29,
    "color": "Indigo",
    "size": "S",
    "material": "polyester",
    "category": "clothing",
    "description": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    "rating": 4.9,
    "availability": false,
    "discount_percentage": 35.72,
    "shipping_cost": 14.78,
    "shipping_time": 6,
    "arrival_date": "4/15/2022",
    "seller_name": "Ailane",
    "seller_rating": 1.4,
    "seller_location": "Suite 81",
    "seller_contact": "333-844-7220"
  }, {
    "product_name": "Mr",
    "brand": "Photobug",
    "price": 117.04,
    "quantity": 77,
    "color": "Turquoise",
    "size": "XL",
    "material": "silk",
    "category": "electronics",
    "description": "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.\n\nQuisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    "rating": 3.0,
    "availability": true,
    "discount_percentage": 40.13,
    "shipping_cost": 18.97,
    "shipping_time": 14,
    "arrival_date": "4/29/2022",
    "seller_name": "Wordpedia",
    "seller_rating": 4.6,
    "seller_location": "Suite 1",
    "seller_contact": "586-147-1125"
  }, {
    "product_name": "Dr",
    "brand": "Voomm",
    "price": 620.79,
    "quantity": 35,
    "color": "Violet",
    "size": "S",
    "material": "cotton",
    "category": "clothing",
    "description": "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    "rating": 4.5,
    "availability": true,
    "discount_percentage": 5.87,
    "shipping_cost": 17.24,
    "shipping_time": 8,
    "arrival_date": "1/26/2022",
    "seller_name": "Brainlounge",
    "seller_rating": 2.9,
    "seller_location": "11th Floor",
    "seller_contact": "153-199-5722"
  }, {
    "product_name": "Mr",
    "brand": "Voolith",
    "price": 51.4,
    "quantity": 94,
    "color": "Violet",
    "size": "M",
    "material": "wool",
    "category": "clothing",
    "description": "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    "rating": 1.3,
    "availability": false,
    "discount_percentage": 22.4,
    "shipping_cost": 9.35,
    "shipping_time": 1,
    "arrival_date": "2/25/2022",
    "seller_name": "Meedoo",
    "seller_rating": 1.8,
    "seller_location": "Suite 83",
    "seller_contact": "370-111-8611"
  }, {
    "product_name": "Mrs",
    "brand": "Meetz",
    "price": 595.45,
    "quantity": 39,
    "color": "Pink",
    "size": "S",
    "material": "wool",
    "category": "clothing",
    "description": "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
    "rating": 1.0,
    "availability": false,
    "discount_percentage": 11.6,
    "shipping_cost": 5.3,
    "shipping_time": 13,
    "arrival_date": "10/5/2022",
    "seller_name": "Skinder",
    "seller_rating": 3.3,
    "seller_location": "Apt 302",
    "seller_contact": "608-969-2214"
  }, {
    "product_name": "Ms",
    "brand": "Jabberstorm",
    "price": 303.25,
    "quantity": 3,
    "color": "Crimson",
    "size": "S",
    "material": "cotton",
    "category": "clothing",
    "description": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    "rating": 4.0,
    "availability": true,
    "discount_percentage": 27.26,
    "shipping_cost": 15.99,
    "shipping_time": 10,
    "arrival_date": "12/1/2022",
    "seller_name": "Wordify",
    "seller_rating": 2.8,
    "seller_location": "9th Floor",
    "seller_contact": "183-217-2708"
  }];

  module.exports = data;